# Numpy 시작하기

## 1. 개요

Numpy는 수치계산을 도와주는 파이썬 라이브러리로 벡터 및 행렬 연산이 용이함

C로 구현되어 성능이 우수함

Numerical Python의 줄임말

Jupyter notebook에서는 별도의 모듈 설치 없이 바로 사용 가능

In [33]:
import numpy as np

Numoy의 버전 확인

In [3]:
np.__version__

'1.16.5'

## 2. Numpy 자료구조
### 1) 배열
Numpy 배열은 파이썬 리스트와 동일한 표기를 사용하나 포함되는 자료형이 모두 동일해야함

Numpy에서 지원하는 자료형으로는

- int
- uint 
- float
- ...
- string
- object
- unicode


배열 생성 및 자료형

In [11]:
lst = [1,2,3,4,5]
print(lst)
print(type(lst))
arr = np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
arr2 = np.array(1,2,3)

ValueError: only 2 non-keyword arguments accepted

ndarry : n-dimensional array

Numpy 배열은 쉼표 없이 표시됨


#### 배열의 크기

len() 함수 사용, 파이썬 함수

In [12]:
len(arr)

5

In [16]:
arr2 = np.array([[1,2,3],[5,6,7]])
arr2

array([[1, 2, 3],
       [5, 6, 7]])

In [17]:
len(arr2)

2

len 함수는 1차원 배열의 요소 갯수를 반환함

전체 원소의 갯수를 구하기 위해서는 Numy의 size() 함수 이용

In [19]:
np.size(arr2)

6

### 배열의 차원

np.ndim()함수 사용

In [21]:
print('arr의 차원: ', np.ndim(arr))
print('arr2의 차원: ', np.ndim(arr2))

arr의 차원:  1
arr2의 차원:  2


각 차원이 몇 개의 원소를 가지는지 알려주는 함수

np.shape() 함수 이용

shape 함수의 경우, 결과값을 튜플 자료구조를 이용하여 출력

In [22]:
print(np.shape(arr))
print(np.shape(arr2))

(5,)
(2, 3)


각 원소의 자료형을 알기 위해서는 배열의 dtype 속성을 확인

In [23]:
print(arr.dtype)

int32


자료형을 변경하기 위해서는 배열의 astype 메소드 활용

In [24]:
arr.astype(float)

array([1., 2., 3., 4., 5.])

문자열로 변경 가능하니 type 명을 np.string_으로 설정해야 함

In [26]:
arr.astype(np.string_)

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S11')




## 2) 배열 생성 함수

np.array() 함수

파이썬의 range() 함수와 유사한 np.arange()함수 사용

이 함수는 ndarray 반환


In [27]:
arr3 = np.arange(3)
print(arr3)
arr4 = np.arange(2,10)
print(arr4)
arr5 = np.arange(2,10,2)
print(arr5)

[0 1 2]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


### linspace, logspace 함수

범위 사이에서 선형간격(linspace), 로그간격(logspace)으로 배열 생성

In [29]:
print(np.linspace(0,1,4))
print(np.logspace(0.1,1,4))

[0.         0.33333333 0.66666667 1.        ]
[ 1.25892541  2.51188643  5.01187234 10.        ]


### zeros, ones, full

특정 값으로 배열을 채워주는 함수

In [32]:
print(np.zeros(3))
print(np.zeros((2,3)))
print(np.ones(4))
print(np.ones((2,3,4)))
print(np.full(3,5))
print(np.full((3,5), 4))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[5 5 5]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


### eye, identity

2차원 항등 행렬 생성

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 차원 변경 함수 reshape

1차원 배열의 차원을 변경

In [36]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
np.arange(3,15).reshape(4,-1)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Numpy DataType

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [2]:
import numpy as np
arr = np.array([1,2,3,4], dtype='S')

In [4]:
arr.dtype

dtype('S1')