## 3. 배열 연산

배열과 배열의 연산, 배열과 스칼라 연산

### 1) 연산자를 이용한 연산

In [1]:
import numpy as np

x = np.array([1,2,3,4,5])
print(x+1)
print(x*2)
print(x%2)

[2 3 4 5 6]
[ 2  4  6  8 10]
[1 0 1 0 1]


In [2]:
y = np.array([5,4,3,2,1])
print(x+y)
print(x*y)
print(x**y)

[6 6 6 6 6]
[5 8 9 8 5]
[ 1 16 27 16  5]


### 2) 함수를 이용한 연산

다양한 기능 제공

In [3]:
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))
print(np.power(x, y))
print(np.mod(x, y))

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]
[ 1 16 27 16  5]
[1 2 0 0 0]


In [4]:
print(np.sqrt(y))
print(np.square(y))
print(np.exp(y))
print(np.log(y))
print(np.log10(y))
print(np.log2(y))

[2.23606798 2.         1.73205081 1.41421356 1.        ]
[25 16  9  4  1]
[148.4131591   54.59815003  20.08553692   7.3890561    2.71828183]
[1.60943791 1.38629436 1.09861229 0.69314718 0.        ]
[0.69897    0.60205999 0.47712125 0.30103    0.        ]
[2.32192809 2.         1.5849625  1.         0.        ]


## 4. 수학 함수

### 1) 실수 

a = np.array([3.14, -5.21, 9.69, -1.87, 0])
print(np.floor(a))
print(np.rint(a))
print(np.around(a))

### 2) 통계 함수

In [9]:
nd = np.random.randn(100)
print(nd)
print(a.sum())
print(np.sum(a))
print(a.mean())
print(np.mean(a))

[-0.10102366 -0.03994026 -0.0304315   1.41727608  0.14437038  0.47642009
  0.54176839 -0.00882779  1.16958908  0.57210992 -1.52924008  1.12067876
 -1.36612141  0.38268883  0.65628235  1.11181087 -1.48489703  0.8334981
 -0.3412575   0.75328857  1.84537236 -1.35064549 -0.73803249  1.66590758
 -0.09281805  0.12641131  0.61032594  0.39412599 -0.16977476  0.61107808
  0.1232323  -1.57064812  0.64564783 -0.13245538  0.16472821 -0.17006966
  0.88109914  0.68853497  2.10621599  0.69864216 -0.29594247 -0.54698061
  0.427897   -1.52665364 -0.42875796  0.69755188 -0.85147912 -0.03521093
  0.54669017  0.53561842  0.80596752 -0.04660778  0.90032304  0.16482206
  0.34138629  0.91530643 -0.37705784  0.07752219 -0.61817192  0.71464581
 -1.39191613 -0.52728932  0.82844165 -0.26046061 -0.83383631  1.76824894
  0.48295801  0.1613443  -0.68072363  0.7154914  -0.92276478  0.71464928
 -0.68534981 -0.53634818  0.61083852  0.49754796 -0.64757263  1.67911652
 -0.69053758 -0.48764995  0.82106812  0.49975985 -0.

In [10]:
print(np.corrcoef(a))
print(np.std(a))
print(np.var(a))

1.0
5.055377335075988
25.55684


In [11]:
print(np.cumsum(a))
print(np.cumprod(a))

[ 3.14 -2.07  7.62  5.75  5.75]
[   3.14        -16.3594     -158.522586    296.43723582    0.        ]


In [15]:
nd2 = np.random.randn(4,5)
print(nd2)

[[-0.35426555  0.46171359  0.10858876  1.01231329  0.13284005]
 [ 0.08991658  0.42610035 -0.4200068   0.74461028  0.59404395]
 [ 0.54441539 -1.6235372   0.07805301  0.75073554 -0.64542222]
 [ 0.43563004  0.20169246 -0.66019265 -1.09747265  0.75009089]]


In [18]:
print(nd2.mean())

0.07649235587955087


In [19]:
print(np.cumsum(nd2))

[-0.35426555  0.10744804  0.2160368   1.22835009  1.36119014  1.45110672
  1.87720707  1.45720027  2.20181055  2.7958545   3.34026989  1.71673269
  1.7947857   2.54552124  1.90009903  2.33572906  2.53742153  1.87722888
  0.77975622  1.52984712]


In [20]:
nd2.sum(axis=0) ## 열 방향

array([ 0.71569646, -0.53403079, -0.89355768,  1.41018645,  0.83155268])

In [21]:
nd2.sum(axis=1) ## 행 방향

array([ 1.36119014,  1.43466436, -0.89575547, -0.37025191])

## 5. 논리 연산 및 행렬 연산(수학적 행렬 연산)

### 1) 논리 연산

In [22]:
a = np.array([0, 1, np.nan, 3, np.inf, np.NINF, np.PINF])

In [23]:
print(a)
print(np.isnan(a))
print(np.isinf(a))
print(np.isneginf(a))
print(np.isposinf(a))
print(np.isfinite(a))

[  0.   1.  nan   3.  inf -inf  inf]
[False False  True False False False False]
[False False False False  True  True  True]
[False False False False False  True False]
[False False False False  True False  True]
[ True  True False  True False False False]


In [24]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 5, 1, 2, 4])
c = np.array([3, 5, 1, 2, 4])

print(np.equal(a, b))
print(np.not_equal(a, b))
print(np.greater(a, b))
print(np.greater_equal(a, b))
print(np.less(a, b))
print(np.less_equal(a, b))
print(np.array_equal(a, b))
print(np.array_equal(b, c))

[False False False False False]
[ True  True  True  True  True]
[False False  True  True  True]
[False False  True  True  True]
[ True  True False False False]
[ True  True False False False]
False
True


### 2) 행렬 연산

In [25]:
a = np.random.randint(0, 10, 4).reshape(2, 2)
b = np.random.randint(0, 10, 4).reshape(2, 2)

print(a)
print(b)

[[5 8]
 [6 8]]
[[9 1]
 [3 0]]


In [26]:
print(a*b) ## 원소별 배열 연산
print(np.multiply(a, b)) ## 원소별 배열 연산
print(np.dot(a, b)) ## 수학적 행렬 연산

[[45  8]
 [18  0]]
[[45  8]
 [18  0]]
[[69  5]
 [78  6]]


In [27]:
print(a)
print(a.T) ## 전치 행렬
print(a.swapaxes(0,1)) ## 축 교환 함수
print(a.transpose(1,0))

[[5 8]
 [6 8]]
[[5 6]
 [8 8]]
[[5 6]
 [8 8]]
[[5 6]
 [8 8]]
