## 3) 배열의 인덱싱/슬라이싱

파이썬 리스트 인덱싱/슬라이싱과 유사

In [1]:
import numpy as np
lst1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
arr1 = np.array(lst1)

In [2]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
## 배열 인덱스를 이용한 참조
arr1[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [4]:
arr1[1:,1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [5]:
arr1[0,]

array([1, 2, 3])

In [6]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
arr1[1,]

array([4, 5, 6])

In [8]:
arr1[1,:]

array([4, 5, 6])

In [9]:
arr1[1]

array([4, 5, 6])

In [10]:
arr1[,1]

SyntaxError: invalid syntax (<ipython-input-10-dde6a3ae52d4>, line 1)

In [11]:
arr1[:,1]

array([ 2,  5,  8, 11])

In [12]:
np.ndim(arr1[:,1])

1

In [13]:
## negative indexing
arr1[-1,:]

array([10, 11, 12])

In [14]:
## [start:end:step]으로 참조 가능
arr1[-1,0:3:2]

array([10, 12])

배열 복사

In [ ]:
arr2 = np.arange(7)
arr3 = arr2[1:5]
print(arr2)
print(arr3)

arr3[2] = 10
print(arr2)
print(arr3)

주소 복사로 모두 변경되었음 이를 피하기 위해서는 copy()함수 사용하여 복사

In [ ]:
arr2 = np.arange(7)
arr3 = arr2[1:5].copy()
print(arr2)
print(arr3)

arr3[2] = 10
print(arr2)
print(arr3)

In [ ]:
arr2[arr2%2 == 0]

In [ ]:
barr2 = arr2%2 == 0

In [ ]:
barr2

### 논리형 인덱싱

특정 조건을 만족하는 원소만을 추출하기 위해 사용

In [ ]:
import numpy as np
arr2 = np.arange(7)
barr2 = arr2%2 == 0
print(arr2)
print(barr2)

In [ ]:
print(arr2[barr2])
print(arr2[arr2%3 == 0])

In [ ]:
subject = np.array(['math', 'math', 'lang', 'chem', 'math', 'phys', 'chem'])
data = np.arange(28).reshape(7, 4)

print(subject)
print(data)

In [ ]:
subject == 'math' ##배열의 논리 연산 결과 배열!!

In [ ]:
data[subject=='math',:] # 0,2,4 행의 모든 열 추출